name: Runner Security Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  security-check:
    runs-on: self-hosted
    steps:
      - name: Run Trivy system audit
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: "fs"
          scan-ref: "/"
          format: "table"
          ignore-unfixed: true
          severity: "HIGH,CRITICAL"
          exit-code: 0
