services:
  web:
    image: ${IMAGE_NAME}
    environment:
      BACKEND_HOST: ${BACKEND_HOST}
      FRONTEND_PORT: ${FRONTEND_PORT:-80}
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=${ENV:-unknown}"
    labels:
      - "environment=${ENV:-unknown}"
    expose:
      - "80"
    networks:
      proxy:

    deploy:
      mode: replicated
      replicas: ${REPLICAS:-2}
      update_config:
        parallelism: 1     # Update one container at a time
        delay: 10s         # Wait 10s between updates
        order: start-first # Start new before stopping old
      restart_policy:
        condition: any
      placement:
        constraints: []
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy:
    external: true
