package be.codeforbelgium.openinzichten.config;

import be.codeforbelgium.openinzichten.domain.Community;
import be.codeforbelgium.openinzichten.domain.Condition;
import be.codeforbelgium.openinzichten.repository.CommunityRepository;
import be.codeforbelgium.openinzichten.repository.ConditionRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.*;

@Configuration
public class ConditionCommunityDataLoader {

    private static final Logger log = LoggerFactory.getLogger(ConditionCommunityDataLoader.class);

    @Bean
    CommandLineRunner loadConditionsAndCommunities(ConditionRepository conditionRepository,
            CommunityRepository communityRepository) {
        return args -> {
            long condCount = conditionRepository.count();
            long commCount = communityRepository.count();

            if (condCount > 0 || commCount > 0) {
                log.info("Aandoeningen ({}) of Gemeenschappen ({}) al aanwezig; overslaan van seed.", condCount,
                        commCount);
                return;
            }

            // 1) Maak gemeenschappen
            String[] communityNames = new String[] {
                    "Algemene Gezondheid",
                    "Hart & Bloeddruk",
                    "Diabetes Ondersteuning",
                    "Geestelijke Gezondheid",
                    "Ademhalingsgezondheid"
            };

            Map<String, Community> communitiesByName = new HashMap<>();
            for (String name : communityNames) {
                Community c = new Community();
                c.setName(name);
                communitiesByName.put(name, communityRepository.save(c));
            }

            // 2) Maak aandoeningen en koppel aan gemeenschappen (Condition is de 'owning
            // side')
            Map<String, List<String>> conditionToCommunities = new HashMap<>();
            conditionToCommunities.put("Hypertensie", List.of("Hart & Bloeddruk"));
            conditionToCommunities.put("Diabetes", List.of("Diabetes Ondersteuning"));
            conditionToCommunities.put("Cholesterol", List.of("Hart & Bloeddruk"));
            conditionToCommunities.put("Astma", List.of("Ademhalingsgezondheid"));
            conditionToCommunities.put("Depressie", List.of("Geestelijke Gezondheid"));
            conditionToCommunities.put("Angststoornis", List.of("Geestelijke Gezondheid"));
            conditionToCommunities.put("Obesitas", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hartfalen", List.of("Hart & Bloeddruk"));
            conditionToCommunities.put("Beroerte", List.of("Hart & Bloeddruk"));
            conditionToCommunities.put("Chronische Nierziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Reuma", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Slaapapneu", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("COPD", List.of("Ademhalingsgezondheid"));
            conditionToCommunities.put("Allergische Rhinitis", List.of("Ademhalingsgezondheid"));
            conditionToCommunities.put("Bipolaire Stoornis", List.of("Geestelijke Gezondheid"));
            conditionToCommunities.put("Osteoporose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kanker", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Multiple Sclerose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Migraine", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Parkinson", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Epilepsie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Psoriasis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronische Leverziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Longkanker", List.of("Ademhalingsgezondheid"));
            conditionToCommunities.put("PTSS", List.of("Geestelijke Gezondheid"));
            conditionToCommunities.put("Eetstoornis", List.of("Geestelijke Gezondheid"));
            conditionToCommunities.put("Schizofrenie", List.of("Geestelijke Gezondheid"));
            conditionToCommunities.put("primaire immuundeficiënties", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Anemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("IJzergebreksanemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Sikkelcelanemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Thalassemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Leukemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lymfoom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronische Myeloïde Leukemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronische Lymfatische Leukemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hemofilie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Trombocytopenie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Vitamine B12 tekort", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Foliumzuurtekort", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronische pijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Fibromyalgie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Complex regionaal pijnsyndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Myalgische encefalomyelitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lymeziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ziekte van Lyme", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lyme borreliose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Borreliosis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ziekte van Pfeiffer", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Epstein-Barr virusinfectie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hepatitis A", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hepatitis B", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hepatitis C", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Auto-immuunhepatitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Heparcirrose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Non-alcoholische leververvetting", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Galstenen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Acute pancreatitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronische pancreatitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Prikkelbare darm syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ziekte van Crohn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Colitis ulcerosa", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Celiakie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lactose-intolerantie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Darmkanker", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Gastro-oesofageale refluxziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ulcussenziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Galklachtaandoening", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Diverticulitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Malabsorptie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kort darm syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronische vermoeidheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Schildklieronderfunctie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hashimoto thyreoïditis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Schildklieroverfunctie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ziekte van Graves", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Nodulaire schildklierziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hypoparathyreoïdie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hyperparathyreoïdie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Diabetes type 1", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Diabetes type 2", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Gesta­tionele diabetes", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Insulineresistentie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Metabool syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hyperthyreoïdie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Adrenal insufficiëntie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Cushingsyndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Addison ziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bijnierhyperplasie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Osteoartritis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Reumatoïde artritis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Juveniele idiopathische artritis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Jicht", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Polymyalgia rheumatica", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spondylitis ankylopoetica", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lupus erythematodes", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Systemische sclerose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Sjögren syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Vasculitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Dermatomyositis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Myositis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bindweefselziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bechterew", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Artrose van de knie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Artrose van de heup", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Carpaal tunnelsyndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Tendinitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bursitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Dupuytren contractuur", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Morton neuroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Achilles tendinopathie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Triggerfinger", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Scoliose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rughernia", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spit (lumbago)", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Whiplash", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Neuropathie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Perifere neuropathie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Diabetische neuropathie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Carcinoïde syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Endometriose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Polycysteus ovarium syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Fibromen in de baarmoeder", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Premenstrueel syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Menopauzale klachten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Dysmenorroe", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Vaginale schimmelinfectie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bacteriële vaginose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Pelvic inflammatory disease", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Borstkanker", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Prostaatkanker", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Testiskanker", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Erectiestoornissen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Blaaskanker", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Interstitiële cystitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Nierstenen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronische nierinsufficiëntie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Nefrotisch syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Glomerulonefritis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Pyelonefritis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Urineweginfectie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overactieve blaas", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Onvruchtbaarheid (mannelijk)", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Onvruchtbaarheid (vrouwelijk)", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Seksueel overdraagbare infecties", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("HIV", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("AIDS", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("HPV infectie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Herpes genitalis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Gonorroe", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chlamydia", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Syfilis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Acne", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Atopische dermatitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Contacteczeem", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Seizoensgebonden allergie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Urticaria", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rosacea", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Vitiligo", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Alopecia areata", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Androgenetische alopecia", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Nagelafwijkingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Huidkanker", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Melanoom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Basaalcelcarcinoom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Plaveiselcelcarcinoom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Psoriatische artritis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichen planus", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hyperhidrosis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hidradenitis suppurativa", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Keratoconus", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Maculadegeneratie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Glaucoom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Cataract", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Retinopathie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Diabetische retinopathie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Netvliesloslating", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Strabismus", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Conjunctivitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Otitis media", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronische otitis media", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Menière ziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Tinnitus", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Geleidingsverlies gehoor", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Sensorineuraal gehoorverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Slaapstoornissen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Insomnie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Narcolepsie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rustelozebenensyndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Circadiane ritmestoornis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Parasomnieën", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("REM-slaap gedragsstoornis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronische migraine", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Clusterhoofdpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spanningshoofdpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Trigeminale neuralgie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bellse parese", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ziekte van Huntington", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ziekte van Alzheimer", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Vasculaire dementie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Frontotemporale dementie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lewy body dementie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ataxie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spierdystrofie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ziekte van Duchenne", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Beckwith-Wiedemann syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Noonan syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Downsyndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Turner syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Klinefelter syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Fragiele X-syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Marfan syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ehlers-Danlos syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Achondroplasie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Perifere arteriële ziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Aneurysma", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Aortaklepstenose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Mitralisklep insufficiëntie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Atriumfibrilleren", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ventriculaire tachycardie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Angina pectoris", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kleine hartafwijkingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Congenitale hartafwijking", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Endocarditis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Myocarditis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Pericarditis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Pulmonale hypertensie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Diepe veneuze trombose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Longembolie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lymfoedeem", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lipoedeem", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hypercholesterolemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Familiaire hypercholesterolemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Dyslipidemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Auto-immuunziekten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Allergieën (voedsel)", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ernstige voedselallergie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Anafylaxie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Astma bij kinderen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bronchiëctasieën", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Interstitiële longziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Pulmonale fibrose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Silicose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Asbestose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Boerenlong (hypersensitiviteitslong)", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Zuurstoftekort", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Acute respiratoir distress syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Pneumonie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Tuberculose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("COVID-19 langdurige klachten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Post-COVID syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Sepsis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bacteriële sepsis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Sepsis met orgaanfalen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Sepsis (langdurige gevolgen)", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Malaria", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Dengue", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Zika virus infectie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chikungunya", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ziekte van Creutzfeldt-Jakob", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rabies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Tetanus", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Polio", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Parvovirus B19 infectie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("RSV infectie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Cytomegalovirus infectie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Herpes zoster (gordelroos)", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Varicella (waterpokken)", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Mononeuritis multiplex", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Guillain-Barré syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Myasthenia gravis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lambert-Eaton syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Neuromusculaire aandoening", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spierziekten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Cerebrale parese", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Periventriculaire leukomalacie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Deformiteiten van de wervelkolom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Botkanker", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Osteomyelitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Osteogenesis imperfecta", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rachitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Botbreuken (pathologisch)", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Scoliose bij adolescenten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spina bifida", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hydrocephalus", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Congenitale afwijkingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Anorectale afwijkingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Voedingsstoornissen bij kinderen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Autismespectrumstoornis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("ADHD", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Taalontwikkelingsstoornis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Leerstoornis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Gedragsstoornis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Intellectuele beperking", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Syndroom van Asperger", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Prader-Willi syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Angelman syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rettsyndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Sensorische verwerkingsstoornis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Leerproblemen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Alcoholverslaving", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Drugsverslaving", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Nicotineverslaving", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Gokverslaving", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Medicatieverslaving", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Stoornis in middelengebruik", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ontwenningssyndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Verslavingsstoorning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Postoperatieve complicaties", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Wondinfectie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chirurgische adhesies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Prothese infectie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Complicaties na bestraling", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Cytopenie na chemotherapie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ernstige neveneffecten medicatie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Allergische reactie op medicijnen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Geneesmiddelintolerantie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ziekten van het bindweefsel", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronische ontsteking", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Immuun-geassocieerde aandoening", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Immuuntherapie bij kanker complicaties", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ooginfecties", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Huidinfecties", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Schaafwond infectie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spataderen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Varicella-zoster complicaties", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hemoroïden", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Anale fissuur", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronische constipatie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Obstructieve slaapapneu", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hypoventilatiesyndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("COPD-exacerbatie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Astma-exacerbatie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hyperventilatie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Paniekaanval", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Dysthyroidie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Stoornissen van de schildklierfunctie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hypercalciëmie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hypocalciëmie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Elektrolytstoornissen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hyponatriëmie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hypernatriëmie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kaliumstoornissen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Magnesiumtekort", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Vitaminedeficiënties", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Obesitas bij kinderen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Eetstoornis binge/purge type", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Orthorexia nervosa", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Pica", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Somatoforme stoornis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Somatisch-symptoomstoornis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hypochondrie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Conversiestoornis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Genderdysforie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Transgender zorgbehoefte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Seksuele disfunctie vrouw", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Vaginisme", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Erectile dysfunctie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Premature ejaculatie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hyperprolactinemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Infertiliteit", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Zwangerschapscomplicaties", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Pre-eclampsie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Eclampsie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Placenta previa", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Placenta abruptio", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Vroeggeboorte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Postpartum depressie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Borstvoedingsproblemen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Neonatale aandoeningen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Jaundice bij pasgeborene", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Respiratoire problemen neonataal", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Congenitale hartafwijking neonataal", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kortademigheid bij kinderen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kinkhoest", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Otitis externa", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Sinusitis chronica", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ziekten van de neusbijholten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Stoornissen van smaak en reuk", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Tandvleesontsteking", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Parodontitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Cariës", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Temporomandibulaire gewrichtsstoornis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kaakmisvorming", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Slaapgerelateerde ademhalingsstoornis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hyperbilirubinemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hemolytische anemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Auto-immuun hemolytische anemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Aplastische anemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Myelodysplastisch syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Polycytemia vera", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Essentiële trombocytose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Trombotisch trombocytopenisch purpura", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Antifosfolipidensyndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronisch verminderde bloedstroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Claudicatio intermittens", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lymfeklierziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lymfomen divers", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Immunodeficiëntie verworven", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Primair immuundeficiënties (overig)", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Congenitale infecties", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ziekte van Kawasaki", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Penyert", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hepatoblastoom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Neuroblastoom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Retinoblastoom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ziekte van Behçet", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Takayasu arteritis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Giant cell arteritis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Eosinofiele oesofagitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronische urinaire retentie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Neurogene blaas", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Pyurie zonder bacteriën", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Barrett slokdarm", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Achalasie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ziek van Hirschsprung", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hemorrhoïdale ziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Anorexia nervosa", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Boulimia nervosa", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Adipositas hypoventilatie syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Morbus Wilson", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hemochromatose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Familiaire amyloïdose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Sikkelcel ziekte trait", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Gluten enteropathie (ernstig)", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lymfangioleiomyomatose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Pulmonale Langerhans-cel histiocytose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bronchiolitis obliterans", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bronchiolitis obliterans syndrome", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Interstitiële cystitis (blaaspijnsyndroom)", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Complexe regionale pijn syndroom type I", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Complexe regionale pijn syndroom type II", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Idiopathische pulmonale fibrose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Pulmonale alveolaire proteïnose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Churg-Strauss syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Morbus Crohn fistelvormend", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Coeliakie met dermatitis herpetiformis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Familiaire mediterrane koorts", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Mastocytose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Histamine intolerantie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Systemische mastocytose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ziekte van Still", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Eosinofiele granulomateuze ziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Gorlin syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Werner syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bloom syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Fanconi anemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kartagener syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Alpha-1 antitrypsine tekort", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Progressieve neurologische aandoening", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spierdystrofie type Becker", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spinale musculaire atrofie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Charcot-Marie-Tooth ziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hereditary spastic paraplegia", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("CADASIL", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("MELAS syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Mitochondriale ziekten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Familiaire hypokalemische periodic paralysis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Periodic paralysis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Familiaire amyloïdose transthyretine", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Alkaptonurie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Fenylketonurie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Homocystinurie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Mucopolysaccharidose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Gaucher ziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Fabry ziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Pompe ziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lysosomale stapelingsziekten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Congenitale immuundeficiëntie (specifiek)", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hyper IgE syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronic granulomatous disease", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Severe combined immunodeficiency", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("DiGeorge syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Wiskott-Aldrich syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ataxia-telangiectasia", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hereditary angioedema", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Angio-oedeem", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Idiopathische trombocytopenische purpura", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hemolytisch-uremisch syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Acute intermitterende porfyrie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronische porfyrie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Autoinflammatoir syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Idiopathische intracraniële hypertensie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Cervicale spondylose", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Thoracale outlet syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Klippel-Feil syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Leigh syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Neurofibromatose type 1", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Neurofibromatose type 2", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Tuberous sclerosis complex", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Sturge-Weber syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Von Hippel-Lindau ziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Polycystische nieren ziekte autosomaal dominant",
                    List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Polycystische nieren ziekte autosomaal recessief",
                    List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Anal incontinentie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Fecale incontinentie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hirschsprung disease adult variant", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Megacolon", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Idiopathische gastroenteritis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Syndroom van Gilbert", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Crigler-Najjar syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Dubin-Johnson syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rotor syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Familiaire hypobetalipoproteïnemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Sitosterolemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lipoproteïnelipase deficiency", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chylomicronemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Familiaire dysbetalipoproteïnemie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Cold agglutinin disease", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Paroxysmale koude hemoglobinurie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Warm autoimmune hemolytic anemia", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Cold autoimmune hemolytic anemia", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Takotsubo cardiomyopathie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Brugada syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Long QT syndroom", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Familiaire aritmie syndromen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Catecholaminergische polymorfe ventriculaire tachycardie",
                    List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Arrhythmogene rechtsventrikel cardiomyopathie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hypertrofische cardiomyopathie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Restrictieve cardiomyopathie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Dilaterende cardiomyopathie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Tourette", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hoofdpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spanningshoofdpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Migraine zonder aura", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Migraine met aura", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Duizeligheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Misselijkheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Braken", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Maagpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Brandend maagzuur", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Diarree", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Obstipatie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Verkoudheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Keelpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hoesten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Loopneus", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Verstopte neus", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Oorpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spierpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Gewrichtspijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rugpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Schouderpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Nekpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Vermoeidheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Slaapproblemen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Prikkelbaarheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Stress", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Huiduitslag", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Jeuk", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Blaarvorming", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Koorts", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rillingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Zweten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Koude rillingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hartkloppingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kortademigheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hyperventilatie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Maagzuur reflux", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Buikpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Opgeblazen gevoel", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Gasvorming", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Winderigheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kramp in de buik", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Menstruatiepijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Premenstrueel ongemak", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hormonale schommelingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Vermoeidheid tijdens zwangerschap", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Misselijkheid tijdens zwangerschap", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spierkrampen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kniepijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Enkelpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Voetpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Tintelingen in handen of voeten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Verlies van gevoel", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Duizeligheid bij opstaan", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bloedneus", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Tandpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Mondzweren", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Droge mond", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Veranderingen in smaak", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Verlies van reuk", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Oogirritatie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Tranende ogen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rode ogen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Wazig zien", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Dubbelzien", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Verminderde concentratie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Geheugenproblemen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Stemmingswisselingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Prikkelbaarheid bij stress", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Angstig gevoel", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rusteloosheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Snel geïrriteerd", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Halsstijfheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Schouderverstijfheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Elleboogpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Polspijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Handpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Vingertintelingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Duimklachten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Heuppijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bekkepijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Menstruatiestoornissen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hormonale acne", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Oorpijn door verkoudheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Sinusitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Allergische verkoudheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Neuspoliepen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Keelontsteking", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Angina", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Amandelontsteking", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Griep", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Influenza", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kinkhoest", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bof", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Waterpokken", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Mazelen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rode hond", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Huidinfecties", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Schimmelinfecties huid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Voetschimmel", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Nagelschimmel", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Herpes simplex", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Koortslip", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Urticaria", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Jeukende huid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Eczeem", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Droge huid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Schilferende huid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rosacea", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Acne", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Huidverkleuring", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Jeukende ogen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Droge ogen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Brandende ogen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rode ogen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ooginfectie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Conjunctivitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bloeddoorlopen ogen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Dubbelzien", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Wazig zien", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichtgevoeligheid ogen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Oorsuizen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Tinnitus", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Gehoorverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Verstopte oren", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Oorontsteking", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Buikgriep", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Voedselvergiftiging", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Darmontsteking", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Prikkelbare darm", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte obstipatie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte diarree", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Opgeblazen buik", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Maagkrampen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Braakneigingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Misselijkheid door reisziekte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Brandend maagzuur door voeding", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Zure oprispingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Licht gevoel in het hoofd", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Flauwvallen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hartkloppingen bij stress", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kortademigheid bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Snel buiten adem", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Benauwdheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Ademhalingsmoeilijkheden", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte verkoudheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Neusverstopping door allergie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Niezen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hooikoorts", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Allergische reactie huid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Allergische reactie ogen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Allergische reactie neus", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Prikkelbare huid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Zwelling van de huid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Bloeduitstorting", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Blauwe plek", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte kneuzing", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Verstuiking", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte verstuiking enkel", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte verstuiking pols", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kneuzing vinger", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spierverrekking", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spierblessure", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overbelasting spier", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Peesontsteking", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Tendinitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte botbreuk", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte schaafwond", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Snijwond", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Brandwond", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte verbranding huid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige vermoeidheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Slaapproblemen door stress", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Insomnia", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Dagdromen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte angst", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Nervositeit", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Rusteloosheid door cafeïne", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Prikkelbaarheid door slaapgebrek", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Concentratieproblemen door vermoeidheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Geheugenproblemen door stress", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Licht depressieve stemming", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Somberheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Emotionele schommelingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Snel geïrriteerd bij vermoeidheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatig gapen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Slaperigheid overdag", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Moeite met opstaan", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Moeite met concentreren", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte hoofdpijn bij stress", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Tension neck", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Oogvermoeidheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Computeroog", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Droge lippen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Blaren op lippen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Verkoudheid gerelateerde hoest", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte keelirritatie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Prikkelbare keel", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hooikoorts gerelateerde vermoeidheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte allergische huidreactie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte oogallergie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Zwelling rond ogen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Verstopte oren door verkoudheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte infectie luchtwegen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Keelontsteking door verkoudheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte koorts door infectie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Verminderde eetlust", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde uitdroging", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Waterverlies door transpiratie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte spierkrampen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spiertrillingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overbelasting pezen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde rugverrekking", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte rugspierblessure", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde botverstijving", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte gewrichtsstijfheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte artritis symptomen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte spierpijn na inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte blauwe plek door stoten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte huidirritatie door kleding", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Droge handen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Gebarsten handen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte nagelirritatie", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Nagelbeschadiging door trauma", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige transpiratie handen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte vermoeidheid door warmte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte duizeligheid door hitte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte misselijkheid door hitte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte koude rillingen door kou", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overgevoeligheid voor kou", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overgevoeligheid voor warmte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte vermoeidheid na inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde spierpijn na inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte hoofdpijn door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte duizeligheid door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte spierverrekking door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde nekpijn door slechte houding", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte rugpijn door houding", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spiervermoeidheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte vermoeidheid na werk", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Slaaptekort", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Jetlag", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatig gapen door slaapgebrek", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte concentratieproblemen door slaapgebrek", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte emotionele uitputting", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Stressgerelateerde hoofdpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spanningshoofdpijn door werk", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde migraineaanval", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte duizeligheid door stress", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte hartkloppingen door stress", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatig transpireren door stress", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Angstreactie door stress", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde paniekaanval", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte rusteloosheid door stress", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Snel geïrriteerd door vermoeidheid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte stemmingswisselingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Somberheid door weersveranderingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte prikkelbaarheid door geluid", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte gevoeligheid voor licht", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Oogirritatie door fel licht", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte oogvermoeidheid door schermen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Droge ogen door omgeving", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte tranende ogen door wind", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte jeuk door insecten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte huidreactie door insectenbeet", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte zwelling door insectenbeet", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte roodheid door insectenbeet", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte jeuk door planten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde huidirritatie door planten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Roodheid door zon", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte zonnebrand", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Oververhitting door zon", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Hittestuwing", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte uitdroging door hitte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Spierkramp door uitdroging", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte vermoeidheid door uitdroging", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige dorst", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte hoofdpijn door uitdroging", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte misselijkheid door uitdroging", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte duizeligheid door uitdroging", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte spierzwakte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige vermoeidheid door werk", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde spierspasmen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte kramp in benen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte kramp in armen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte rugkramp", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde gewrichtspijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte zwelling van gewrichten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte stijfheid van gewrichten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde artritis symptomen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte botpijn", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte botverstijving", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde osteoporose klachten", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte spierpijn bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte vermoeidheid bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte duizeligheid bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde hartkloppingen bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kortademigheid bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige transpiratie bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte spiervermoeidheid bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte rugpijn bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte nekpijn bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde spierverrekking bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte spierblessure bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte overbelasting van pezen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde peesontsteking", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte tendinitis", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte verstuiking bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte blauwe plek bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte huidirritatie bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte uitslag bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte jeuk bij inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige vermoeidheid door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte slapeloosheid door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Slaaptekort door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte concentratieproblemen door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Geheugenproblemen door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte stemmingswisselingen door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde somberheid door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte prikkelbaarheid door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte angst door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte rusteloosheid door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Snel geïrriteerd door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige transpiratie door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte duizeligheid door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde misselijkheid door inspanning", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte vermoeidheid door hitte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte vermoeidheid door kou", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte rillingen door kou", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige dorst door hitte", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige dorst door kou", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte hoofdpijn door temperatuurwisselingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte duizeligheid door temperatuurwisselingen",
                    List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte misselijkheid door temperatuurwisselingen",
                    List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige vermoeidheid door temperatuurwisselingen",
                    List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte spierpijn door temperatuurwisselingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte gewrichtspijn door temperatuurwisselingen",
                    List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte stijfheid door temperatuurwisselingen", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde spierkrampen door temperatuurwisselingen",
                    List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte kramp in benen door temperatuurwisselingen",
                    List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte kramp in armen door temperatuurwisselingen",
                    List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige transpiratie door temperatuurwisselingen",
                    List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte duizeligheid door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte misselijkheid door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte vermoeidheid door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte spierzwakte door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige dorst door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte hoofdpijn door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte hartkloppingen door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Kortademigheid door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige transpiratie door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte spiervermoeidheid door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte rugpijn door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte nekpijn door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde spierverrekking door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte spierblessure door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte overbelasting pezen door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde peesontsteking door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte tendinitis door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte verstuiking door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte blauwe plek door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte huidirritatie door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte uitslag door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte jeuk door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige vermoeidheid door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte slapeloosheid door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Slaaptekort door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte concentratieproblemen door vochtverlies",
                    List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Geheugenproblemen door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte stemmingswisselingen door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde somberheid door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte prikkelbaarheid door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte angst door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte rusteloosheid door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Snel geïrriteerd door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Overmatige transpiratie door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Lichte duizeligheid door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Milde misselijkheid door vochtverlies", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Chronische vermoeidheidssyndroom (CVS) ", List.of("Algemene Gezondheid"));
            conditionToCommunities.put("Functionele Neurologische Stoornis (FNS)", List.of("Algemene Gezondheid"));



            List<Condition> toSave = new ArrayList<>();
            for (Map.Entry<String, List<String>> e : conditionToCommunities.entrySet()) {
                Condition condition = new Condition();
                condition.setName(e.getKey());
                Set<Community> links = new HashSet<>();
                for (String commName : e.getValue()) {
                    Community comm = communitiesByName.get(commName);
                    if (comm != null) {
                        links.add(comm);
                    }
                }
                condition.setCommunities(links);
                toSave.add(condition);
            }

            conditionRepository.saveAll(toSave);
            log.info("Gezaaid: {} gemeenschappen en {} aandoeningen.", communitiesByName.size(), toSave.size());
        };
    }
}
